name: CI

on: [push, pull_request]

env:
  DEPLOYMENT_ENV: "false"
  POSTGRES_URL: "https://fake.com"
  POSTGRES_PRISMA_URL: "https://fake.com"
  POSTGRES_URL_NO_SSL: "https://fake.com"
  POSTGRES_URL_NON_POOLING: "https://fake.com"
  POSTGRES_USER: "default"
  POSTGRES_HOST: "host"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DATABASE: "database"
  ALPACA_LIVE_KEY: "fakeKey"
  ALPACA_LIVE_SECRET: "fakeKey"
  ALPACA_PAPER_KEY: "fakeKey"
  ALPACA_PAPER_SECRET: "fakeKey"
  SENTRY_AUTH_TOKEN: "fakeToken"
  ALPACA_TRADINGVIEW_SYMBOLS: "{}"
  ALPACA_TRADINGVIEW_INVERSE_PAIRS: "{}"
  TRADINGVIEW_AUTH_TOKEN: "fakeToken"
  DEVELOPMENT_MODE: "false"
  FINANCIAL_YEAR_PERIOD: "Jan-Dec"
  QSTASH_URL: "https://fake.com"
  QSTASH_TOKEN: "fakeToken"
  QSTASH_CURRENT_SIGNING_KEY: "fakeKey"
  QSTASH_NEXT_SIGNING_KEY: "fakeKey"
  BYBIT_LIVE_KEY: "fakeKey"
  BYBIT_LIVE_SECRET: "fakeKey"
  BYBIT_PAPER_KEY: "fakeKey"
  BYBIT_PAPER_SECRET: "fakeKey"
  BYBIT_TRADINGVIEW_SYMBOLS: "{}"
  BYBIT_TRADINGVIEW_INVERSE_PAIRS: "{}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        working-directory: ./orders

      - name: Typecheck
        run: pnpm run typecheck
        working-directory: ./orders

      - name: Lint
        run: pnpm run lint
        working-directory: ./orders

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
        working-directory: ./orders

      - name: Unit Tests
        run: pnpm run test
        working-directory: ./orders